#
# Docker image with Snapdragon Flight SDK for Eagle board.
# The image contains trimmed versions of the Hexagon SDK and
# qrlSDK.
#
# Run the minimalSDK.sh script to create the 
# cross_toolchain/minimalSDK.tgz file used below.
#

FROM atlflight/minimal_sdk
MAINTAINER Mark Charlebois <charlebm@gmail.com>

RUN git clone https://github.com/ATLFlight/dspal.git \
    && cd dspal/test \
    && make \
    && echo "Successfully built DSPAL tester"
