#
# Docker image with Snapdragon Flight SDK for Eagle board.
# The image contains trimmed versions of the Hexagon SDK and
# qrlSDK.
#
# Run the minimalSDK.sh script to create the 
# cross_toolchain/minimalSDK.tgz file used below.
#

FROM ubuntu:xenial
MAINTAINER Mark Charlebois <charlebm@gmail.com>

RUN apt-get update \
    && apt-get -y --quiet --no-install-recommends install \
    binutils \
    file \
    git \
    make \
    ccache \
    cmake \
    unzip \
    xz-utils \
    ca-certificates \
    ssh \
    python \
    && apt-get -y autoremove \
    && apt-get clean autoclean

ADD sdk/cross_toolchain/minimalSDK.tgz \
    /opt/

ENV HEXAGON_SDK_ROOT="/opt/Qualcomm/Hexagon_SDK/3.0"
ENV HEXAGON_TOOLS_ROOT="/opt/Qualcomm/HEXAGON_Tools/7.2.12/Tools"
ENV HEXAGON_ARM_SYSROOT="/opt/Qualcomm/qrlinux_v4_sysroot/merged-rootfs"

ENV PATH="${HEXAGON_SDK_ROOT}/gcc-linaro-4.9-2014.11-x86_64_arm-linux-gnueabihf_linux/bin":$PATH

ENV GIT_SSL_NO_VERIFY=true
ENV PATH "/usr/lib/ccache:$PATH"
ENV DISPLAY :0
ENV TERM=xterm
ENV CCACHE_CPP2=1

RUN adduser --shell /bin/bash --disabled-password --gecos '' --uid 9001 user
USER user

CMD ["/bin/bash"]
